###
GET http://localhost:3000/test

###
GET http://localhost:3000/api/quotes

###
GET http://localhost:3000/api/quotes/1

###
POST http://localhost:3000/api/quotes
Content-Type: application/json

{
  "quote": "this is a test quote"
}

###
PATCH http://localhost:3000/api/quotes/1
Content-Type: application/json

{
  "quote": "Newest quote"
}

###
DELETE http://localhost:3000/api/quotes/1